import {
  Bath,
  Waves,
  Droplet,
  Flame,
  Snowflake,
  Mountain,
  MountainSnow,
  CableCar,
  Bike,
  Trees,
  Leaf,
  Flower2,
  Sun,
  Umbrella,
  Tent,
  Fish,
  Sailboat,
  Anchor,
  Kayak,
  Sunrise,
  Sunset,
  Palmtree,
  Compass,
  Map,
  Navigation,
  Car,
  ParkingSquare,
  Bus,
  Train,
  Plane,
  Home,
  Bed,
  Sofa,
  Lamp,
  Key,
  Lock,
  Wifi,
  Tv,
  Gamepad,
  Music,
  Camera,
  Utensils,
  Coffee,
  Wine,
  CookingPot,
  ChefHat,
  Pizza,
  Refrigerator,
  Microwave,
  WashingMachine,
  ShowerHead,
  Thermometer,
  Wind,
  Zap,
  Dumbbell,
  Heart,
  Star,
  Sparkles,
  Gift,
  Calendar,
  Clock,
  Phone,
  Info,
  Book,
  FileText,
  Clipboard,
  Shield,
  Dog,
  Cat,
  Baby,
  Accessibility,
  Store,
  Recycle,
  Trash,
  type LucideIcon,
} from "lucide-react"

const ICON_MAP: Record<string, LucideIcon> = {
  bath: Bath,
  waves: Waves,
  droplet: Droplet,
  flame: Flame,
  snowflake: Snowflake,
  mountain: Mountain,
  "mountain-snow": MountainSnow,
  "cable-car": CableCar,
  bike: Bike,
  trees: Trees,
  leaf: Leaf,
  "flower-2": Flower2,
  sun: Sun,
  umbrella: Umbrella,
  tent: Tent,
  fish: Fish,
  sailboat: Sailboat,
  anchor: Anchor,
  kayak: Kayak,
  sunrise: Sunrise,
  sunset: Sunset,
  palmtree: Palmtree,
  compass: Compass,
  map: Map,
  navigation: Navigation,
  car: Car,
  "parking-square": ParkingSquare,
  bus: Bus,
  train: Train,
  plane: Plane,
  home: Home,
  bed: Bed,
  sofa: Sofa,
  lamp: Lamp,
  key: Key,
  lock: Lock,
  wifi: Wifi,
  tv: Tv,
  gamepad: Gamepad,
  music: Music,
  camera: Camera,
  utensils: Utensils,
  coffee: Coffee,
  wine: Wine,
  "cooking-pot": CookingPot,
  "chef-hat": ChefHat,
  pizza: Pizza,
  refrigerator: Refrigerator,
  microwave: Microwave,
  "washing-machine": WashingMachine,
  shower: ShowerHead,
  thermometer: Thermometer,
  wind: Wind,
  zap: Zap,
  dumbbell: Dumbbell,
  heart: Heart,
  star: Star,
  sparkles: Sparkles,
  gift: Gift,
  calendar: Calendar,
  clock: Clock,
  phone: Phone,
  info: Info,
  book: Book,
  "file-text": FileText,
  clipboard: Clipboard,
  shield: Shield,
  dog: Dog,
  cat: Cat,
  baby: Baby,
  accessibility: Accessibility,
  store: Store,
  recycle: Recycle,
  trash: Trash,
}

export function getIcon(name?: string): LucideIcon {
  if (name && ICON_MAP[name]) return ICON_MAP[name]
  return FileText
}
