export { useStaticContent } from "./useStaticContent"
export { useGuide } from "./useGuide"
export { useValidateCode } from "./useValidateCode"
export { getSlug, setSlug, clearSlug } from "./useAccessCode"
export { useGuideContext } from "./guideContext"
export { default as GuideProvider } from "./GuideProvider"
export { useLocale, LocaleProvider, LOCALES, LOCALE_LABELS } from "./useLocale"
export type { Locale } from "./useLocale"
